stages:
- name: Build Frontend
  steps:
  - publishImageConfig:
      dockerfilePath: ./frontend/Dockerfile
      buildContext: ./frontend
      tag: weather/frontend:v1
      pushRemote: true
      registry: 127.0.0.1:34772
- name: Build Backend
  steps:
  - publishImageConfig:
      dockerfilePath: ./backend/Dockerfile
      buildContext: ./backend
      tag: backendr:${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: 127.0.0.1:34772
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
