#---
#
## tasks file for ansible-dockerized-wordpress
#
#- name: "Launch container"
#
#- name: Nginx deployment
#  hosts: '{{ target }}'
#  tasks:
#  - docker_image:
#      name: nginx
#  - docker_service:
#      project_name: nginx_sample
#      project_src: '.'
